llm:
  type: baidu  
  models:
    baidu: sqv0dsdt_n4v4  
  api_keys:
    baidu: "yourapikey"
  temperature: 0.7

benchmark:
  checkpoint: "checkpoints"
  verbose: true
  output_pattern: "results/{dataset_name}_{model}_finetuned.json"
