llm:
  type: openai
  models:
    openrouter: Null
    openai: "tinyllama"
    anthropic: Null
  api_keys:
    openrouter: ""
    openai: "sk-XXXXXXXXXXXXXXXXXXXX"
    anthropic: ""
  temperature: 0.7
  base_url: "http://127.0.0.1:8080/v1/"

benchmark:
  checkpoint: "checkpoints"
  verbose: true
  output_pattern: "results/{dataset_name}_{model}.json"

